const mongoose = require("mongoose");

/**
 * ==========================================================
 * Auth User Schema
 * ==========================================================
 *
 * Stores Internet Banking credentials only.
 * Customer profile remains in Fineract.
 *
 * One Internet Banking user per external account.
 * ==========================================================
 */

const AuthUserSchema = new mongoose.Schema(
    {
        /**
         * External Account Number
         * Generated by Account Service.
         */
        accountNumber: {
            type: String,
            required: true,
            unique: true,
            index: true,
            trim: true
        },

        /**
         * Fineract Client ID
         */
        clientId: {
            type: String,
            required: true,
            index: true
        },

        /**
         * Username
         */
        username: {
            type: String,
            required: true,
            unique: true,
            lowercase: true,
            trim: true,
            minlength: 4,
            maxlength: 30,
            index: true
        },

        /**
         * Email
         */
        email: {
            type: String,
            required: true,
            lowercase: true,
            trim: true,
            index: true
        },

        /**
         * Phone Number
         */
        phoneNumber: {
            type: String,
            required: true,
            trim: true,
            index: true
        },

        /**
         * Password Hash
         */
        passwordHash: {
            type: String,
            required: true
        },

        /**
         * Registration Status
         */
        status: {
            type: String,
            enum: [
                "PENDING",
                "ACTIVE",
                "LOCKED",
                "DISABLED"
            ],
            default: "PENDING",
            index: true
        },

        /**
         * Failed Login Attempts
         */
        failedLoginAttempts: {
            type: Number,
            default: 0
        },

        /**
         * Lock Expiry
         */
        lockedUntil: {
            type: Date,
            default: null
        },

        /**
         * Last Successful Login
         */
        lastLoginAt: {
            type: Date,
            default: null
        },

        /**
         * Password Changed
         */
        passwordChangedAt: {
            type: Date,
            default: null
        },

        /**
         * Email Verified
         */
        emailVerified: {
            type: Boolean,
            default: false
        },

        /**
         * Phone Verified
         */
        phoneVerified: {
            type: Boolean,
            default: false
        }
    },
    {
        timestamps: true,
        versionKey: false
    }
);

/**
 * ==========================================================
 * Indexes
 * ==========================================================
 */

AuthUserSchema.index({
    accountNumber: 1
});

AuthUserSchema.index({
    username: 1
});

AuthUserSchema.index({
    email: 1
});

AuthUserSchema.index({
    phoneNumber: 1
});

AuthUserSchema.index({
    clientId: 1
});

module.exports = mongoose.model(
    "AuthUser",
    AuthUserSchema
);
